### ISSUE TITLE
Get Entire File Url

### ISSUE THREAD

**Issue by Ethanpolley** [nazirov91/ra-strapi-rest#19]
By Default, when strapi is returning the url to an image it only returns beginning with the "/uploads/[id]". Is there anyway to get the entire url to return so that we can use the ImageField Elements in ReactAdmin?

**Comment by nazirov91** [comment]
@Ethanpolley You can still use the ImageField element without the entire URL.

```js
<ImageField source="<Name_of_the_image_field>" src="url" />
```

For example,

```js
<ImageField source="images" src="url" />
```

Is `ImageField` element currently not working for you or do you have any specific need to utilize the full image URL?

Also, having the ID of the image, you could easily add the `localhost:1337` to the beginning, which would then be the full image URL.

```js
http://localhost:1337/uploads/0467e62f8dd94652928d9150f9b87476.png
```

**Comment by Ethanpolley** [comment]
The issue is that i am running my react app from port 3000 (so the link is localhost:3000), but I am running my strapi api from port 1337. Thus, when I load the image field, it tries to access the photos from localhost:3000/uploads/[file_id] instead of from the strapi api, localhost:1337/uploads/[file_id]

**Comment by nazirov91** [comment]
Do you have this `"proxy": "http://localhost:1337"` in your `package.json` of your react app?

**Comment by Ethanpolley** [comment]
That Worked! You are a miracle worker thank you so much!

**Comment by nazirov91** [comment]
No problem. Good luck!

**Comment by PvtAnimalMother** [comment]
How can i add proxy to production build?
http-proxy-middleware doesnt work
![image](https://user-images.githubusercontent.com/66620644/119660081-8348d800-be37-11eb-9868-a28147bb30c6.png)
![image](https://user-images.githubusercontent.com/66620644/119660153-96f43e80-be37-11eb-922f-c87518ea1862.png)
