### ISSUE TITLE
TypeError: _dataProvider_server_rest__WEBPACK_IMPORTED_MODULE_3__.strapiDataProvider.getOne is not a function

### ISSUE THREAD

**Issue by rizshivalli** [nazirov91/ra-strapi-rest#21]
I am trying to perform a simple fetch with strapi rest. I am able to fetch the data with Resource from react-admin but when i want to fetch a single record with custom query or a getList in useEffect i am not able to do so  

````
import simpleRestProvider from 'ra-strapi-rest';

const strapiDataProvider = simpleRestProvider(
  'http://localhost:1337'
);

 useEffect(() => {   
    strapiDataProvider
      .getList('customers')
      .then((data: any) => {
        console.log('data: ', data);
      })
      .catch((error: any) => {
        console.log('error: ', error);
      });
  }, []); 

````
I am getting following error 

>TypeError: _dataProvider_server_rest__WEBPACK_IMPORTED_MODULE_3__.strapiDataProvider.getList is not a function

I have also tried to get a single record 
````
 useEffect(() => {
    strapiDataProvider
      .getOne('customers', { id: 61 })
      .then((data:any) => {
        console.log('data: ', data);
      })
      .catch((error: any) => {
        console.log('error: ', error);
      });
  }, []);
````

I am getting same error for the above as well

>TypeError: _dataProvider_server_rest__WEBPACK_IMPORTED_MODULE_3__.strapiDataProvider.getOne is not a function

What am i doing wrong?

**Comment by nazirov91** [comment]
You should be able to implement it by using the `useQuery` hook or `<Query>` component. The data provider does not have individual functions for each request (getOne, getList etc.). It recognizes `type`, `resource` and `payload`.

```js
import React from 'react';
import { useQuery, Loading, Error } from 'react-admin';

// GET ONE
const GetCustomer = ({ customerId }) => {
    const { data, loading, error } = useQuery({ 
        type: 'GET_ONE',
        resource: 'customers',
        payload: { id: customerId }
    });

    if (loading) return <Loading />;
    if (error) return <Error />;
    if (!data) return null;

    return (
        <ul>
            <li>Name: {data.name}</li>
            <li>Email: {data.email}</li>
        </ul>
    )
};

// GET LIST
import { Query, Loading, Error } from 'react-admin';

const payload = {
   pagination: { page: 1, perPage: 10 },
   sort: { field: 'name', order: 'ASC' },
};

const GetCustomerList = () => (
    <Query type='GET_LIST' resource='customers' payload={payload}>
        {({ data, total, loading, error }) => {
            if (loading) { return <Loading />; }
            if (error) { return <Error />; }
            return (
                <div>
                    <p>Total customers: {total}</p>
                    <ul>
                        {data.map(customer => <li key={customer.id}>{customer.name}</li>)}
                    </ul>
                </div>
            );
        }}
    </Query>
);
```

Please note the use of `GET_LIST` and `GET_ONE` instead of `getOne` and `getList`.

**Comment by rizshivalli** [comment]
Thank You @nazirov91 for replying.

I have tried the solution that you have provided for GET_ONE and GET_LIST. 
Unfortunately GET_ONE api call is throwing ` 500 Internal Server Error `  and ` Error
    at new HttpError (HttpError.js:29)
    at fetch.js:58 `.

 And GET_LIST is throwing the following error 
` error:  Error: The dataProvider threw an error. It should return a rejected Promise instead. `.

**Comment by rizshivalli** [comment]
I was able to resolve GET_ONE api call by replacing
 ````  url = `${apiUrl}/${resource}/${params.id}`;  ```` with  ````  url = `${apiUrl}\\${resource}\\${params.id}`;  ````  but the GET_LIST issue still persist.

**Comment by nazirov91** [comment]
custom queries are not supported with this tool at the moment. It will be updated soon and I will add the instructions when it does. Thanks!

**Comment by faisal212** [comment]
nazirov91  custom queries still not added
