### ISSUE TITLE
Has and belongs to many relation

### ISSUE THREAD

**Issue by EdgarGomez** [nazirov91/ra-strapi-rest#27]
Hello!

I'm facing another problem. In this case with the Has and belongs to many relation from Strapi.

Example, I have an entity called users and an entity called projects. Users are assigned to multiple projects and a project has many users assigned.

This is supposed to be working in react admin with something like:
- In create/edit:
```
<ReferenceArrayInput
          source="project"
          reference="projects"
          label="Projects"
        >
          <SelectArrayInput optionText="name" label="Choose project" />
        </ReferenceArrayInput>
```

- In show view:
```
      <ReferenceArrayField source="project" reference="projects">
        <SingleFieldList>
          <ChipField source="name" />
        </SingleFieldList>
      </ReferenceArrayField>
```

I've tried on source adding .id, .ids, _ids but is not working. Any idea why? Thanks!

**Comment by faisal212** [comment]
has you find the solution?
