### ISSUE TITLE
Handle Strapi validation errors

### ISSUE THREAD

**Issue by nextglabs** [nazirov91/ra-strapi-rest#28]
I'm using Strapi for the backend and `ra-strapi-rest` dataProvider in `react-admin` but I'm experiencing some issues.

For instance, Strapi sends a `ValidationError` this way:
`{"statusCode":400,"error":"Bad Request","message":"ValidationError","data":{"errors":{"members":["members must be greater than or equal to 1"]}}}`·

This results in a single error Notification on `react-admin` which only displays: "ValidationError" instead of a more descriptive error or errors. 

Any ideas on how to fix this?

**Comment by nazirov91** [comment]
@nextglabs That error message is most likely because of members model setup in your strapi - [Strapi Model Validations](https://strapi.io/documentation/v3.x/concepts/models.html#define-the-attributes)

For example, `title` below must be greater than or equal to 3. Otherwise it will throw `ValidationError`
```js
{
  ...
  "attributes": {
    "title": {
      "type": "string",
      "min": 3,
      "max": 99,
      "unique": true
    },
    "description": {
      "default": "My description",
      "type": "text",
      "required": true
    },
    "slug": {
      "type": "uid",
      "targetField": "title"
    }
    ...
  }
}
```

**Comment by nextglabs** [comment]
@nazirov91 thanks for your reply. I am aware of these strapi model validations. I have configured those myself to avoid saving invalid data in the database. 

The problem is that those validation errors are not properly displayed in the front-end because they don't explain exactly why there was a validationError or which field/fields where invalid. It just says "ValidationError" which is a terrible user experience.

I think the root cause is the fact that the error handling ist just returning the error.message instead of checking if there are multiple errors to display.

Please advise.

**Comment by nazirov91** [comment]
I see. 
Agreed, not showing the actual reason for the error is not a good UX. However, in this data provider, the only place where an error is handled is the incorrect action type request situation.

I would think that adding `catch` clause to each Promise call would be a good place to start. I have not tested it yet, but you could try to handle the fail option for all promises in this provider (counted 6 of them)

```js
...
.then(responses => ({
   data: responses.map(response => response.json),
}))
.catch(e => console.log(e)); // <-- ADD THIS to all promise executions. You could replace console with something else if needed
```

Please let me know how it works out. 

Thanks!

**Comment by nazirov91** [comment]
no response. closing
