### ISSUE TITLE
Single-Type Support

### ISSUE THREAD

**Issue by d-bari** [nazirov91/ra-strapi-rest#35]
### Single-Type 
**What is the Behaviour of single-type resource**

1. Is it Possible to extend the dataProvider for special cases?
2.It is very curricial for Strapi user , it is used commonly for app settings
![del](https://user-images.githubusercontent.com/62821447/145032462-f4702980-318e-4584-99bb-95f1f46e86d8.PNG)

**Comment by nazirov91** [comment]
Hi! 

Please see the readme file. I have updated the package to make it work with Strapi V4. Please open a new issue if the problem persists. 

Thanks!
