### ISSUE TITLE
Data UPDATE does not work correctly

### ISSUE THREAD

**Issue by quiqrt** [nazirov91/ra-strapi-rest#4]
Strapi refuses to update data due to the `created_at` and `updated_at` fields in the request. A possible solution would be to remove these fields from params.data. Or you can limit the updated data in the react-admin itself?

Problem code

```
case UPDATE:
                url = `${apiUrl}/${resource}/${params.id}`;
                options.method = 'PUT';
                delete params.data["created_at"];
                delete params.data["updated_at"];
                options.body = JSON.stringify(params.data);
                break;
```

**Comment by nazirov91** [comment]
@windowliker Thank you for pointing that out! It really is an issue. I already implemented this in my project but forgot to add it here. Below is a cleaner way of doing it:

```js
case UPDATE:
     url = `${apiUrl}/${resource}/${params.id}`;
     options.method = 'PUT';
     const {created_at, updated_at, createdAt, updatedAt, ...data} = params.data;
     options.body = JSON.stringify(data);
     break;
```

Relational databases use `created_at` and `updated_at`, NoSQL uses `createdAt` and `updatedAt`, so it is better to keep them all there to make sure it works regardless of the database type.


Also UPDATE_MANY section needs to have this modification

```js
if (type === UPDATE_MANY) {
    return Promise.all(
        params.ids.map(id => {
            const {created_at, updated_at, createdAt, updatedAt, ...data} = params.data; // <<--- 
            return httpClient(`${apiUrl}/${resource}/${id}`, {
                method: 'PUT',
                body: JSON.stringify(data),
            })}
        )
    ).then(responses => ({
        data: responses.map(response => response.json),
    }));
}
```

Please refer to the *index.js* for updated version.
